version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
